# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: fm_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: fm_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: fm_production
  pool: 5
  username: apprentice
  password:
