module ApplicationHelper
  def football_teams
    teams = Team.pluck(:home_city).zip(Team.pluck(:team_name)).map { |team| team.join(' ') }
    teams.zip(Team.pluck(:id)).sort
  end

  def sf_neighborhoods 
    [
      ['Alamo Square', 'Alamo Square'],
      ['Anza Vista', 'Anza Vista'],
      ['Ashbury Heights', 'Ashbury Heights'],
      ['Balboa Terrace', 'Balboa Terrace'], 
      ['Bayview-Hunters Point', 'Bayview-Hunters Point'],
      ['Bernal Heights','Bernal Heights'],
      ['Castro', 'Castro'],
      ['Chinatown', 'Chinatown'],
      ['Civic Center', 'Civic Center'],
      ['Cole Valley', 'Cole Valley'],
      ['Crocker-Amazon', 'Crocker-Amazon'],
      ['Diamond Heights', 'Diamond Heights'],
      ['Dogpatch', 'Dogpatch'],
      ['Embarcadero', 'Embarcadero'],
      ['Excelsior', 'Excelsior'],
      ['Fillmore', 'Fillmore'],
      ['Financial District', 'Financial District'],
      ["Fisherman's Wharf", "Fisherman's Wharf"],
      ['Forrest Hill', 'Forest Hill'],
      ['Glen Park', 'Glen Park'],
      ['Haight-Ashbury', 'Haight-Ashbury'],
      ['Hayes Valley', 'Hayes Valley'],
      ['Ingleside', 'Ingleside'],
      ['Ingleside Heights', 'Ingleside Heights'],
      ['Ingleside Terraces', 'Ingleside Terraces'],
      ['Inner Richmond', 'Inner Richmond'],
      ['Inner Sunset', 'Inner Sunset'],
      ['Japantown', 'Japantown'],
      ['Lakeshore', 'Lakeshore'],
      ['Lakeside', 'Lakeside'],
      ['Laurel Heights', 'Laurel Heights'],
      ['Lower Haight', 'Lower Haight'],
      ['Lower Pacific Heights', 'Lower Pacific Heights'],
      ['Marina/Cow Hollow', 'Marina/Cow Hollow'],
      ['Merced Heights', 'Merced Heights'],
      ['Merced Manor', 'Merced Manor'],
      ['Miraloma Park', 'Miraloma Park'],
      ['Mission', 'Mission'],
      ['Mission Terrace', 'Mission Terrace'],
      ['Monterey Heights', 'Monterey Heights'],
      ['Mount Davidson Manor', 'Mount Davidson Manor'],
      ['Nob Hill', 'Nob Hill'],
      ['Noe Valley', 'Noe Valley'],
      ['NoPa', 'NoPa'],
      ['North Beach/Telegraph Hill', 'North Beach/Telegraph Hill'],
      ['Oceanview', 'Oceanview'],
      ['Outer Mission', 'Outer Mission'],
      ['Outer Richmond', 'Outer Richmond'],
      ['Outer Sunset', 'Outer Sunset'],
      ['Pacific Heights', 'Pacific Heights'],
      ['Parkmerced', 'Parkmerced'],
      ['Parkside', 'Parkside'],
      ['Portola', 'Portola'],
      ['Potrero Hill', 'Potrero Hill'],
      ['Presidio', 'Presidio'],
      ['Presidio Heights', 'Presidio Heights'],
      ['Russian Hill', 'Russian Hill'],
      ['Sea Cliff', 'Sea Cliff'],
      ['Sherwood Forest', 'Sherwood Forest'],
      ['SoMa', 'SoMa'],
      ['St Francis Wood', 'St Francis Wood'],
      ['Stonestown', 'Stonestown'],
      ['Sunnyside', 'Sunnyside'],
      ['Tenderloin', 'Tenderloin'],
      ['Twin Peaks', 'Twin Peaks'],
      ['Union Square', 'Union Square'],
      ['Visitacion Valley', 'Visitacion Valley'],
      ['West Portal', 'West Portal'],
      ['Western Addition', 'Western Addition'],
      ['Westwood Highlands', 'Westwood'],
      ['Westwood Park', 'Westwood Park']
    ] 
  end

  def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end
end
